config/routes.rb
Rails.application.routes.draw do
  resources :pending_applications
  resources :photography_jobs do 
    resources :job_applications
  end
  resources :job_applications
  root to: "home#index"
  resources :photography_jobs
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  resources :profiles, only: %i[edit update show]
end

app/models/photography_job.rb
# == Schema Information
#
# Table name: photography_jobs
#
#  id          :bigint           not null, primary key
#  completed   :boolean          default(FALSE)
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#  users_id    :integer
#
# Indexes
#
#  index_photography_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class PhotographyJob < ApplicationRecord
  belongs_to :user
  has_many :applications
  has_many :pending_applications, through: :applications
  has_many :users, as: :applicants, through: :applications, dependent: :destroy
end

app/controllers/photography_jobs_controller.rb
class PhotographyJobsController < ApplicationController
    before_action :set_user, only: %i[create edit]
    before_action :set_job, only: %i[show]
    
    def index 
        @jobs = PhotographyJob.all
    end

    def new
       @photographyjob = PhotographyJob.new
    end

    def create
        @photographyjob = @user.photography_jobs.create(photography_job_params)
        if @user.save
            redirect_to profile_path(@user)
        else 
            render 'new'
        end
    end

    def show
    end 

    private
    def set_job
        @photographyjob = PhotographyJob.find_by_id(params[:id])
    end

    def set_user
        @user = User.find_by_id(current_user.id)
    end

    def photography_job_params
        params.require(:photography_job).permit(:title,:description)
    end
end

app/helpers/photography_jobs_helper.rb
module PhotographyJobsHelper
end

app/views/photography_jobs/_form.html.erb
<%= form_with model: @photographyjob do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <%= f.submit 'Create ' %>
<% end %>

app/views/photography_jobs/index.html.erb
        <h1 class="header">Jobs Board</h1>
        <% if !@jobs.empty? %>
            <ul>
                <% @jobs.each do |f|%>
                    <%=link_to f.title, photography_job_path(f)%>
                <% end%>
            </ul>
        <% else%>
            <h2>No jobs available</h2>
        <% end %>
    </div>
</div>

app/views/photography_jobs/new.html.erb
<%= form_with model: @photographyjob do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <%= f.submit 'Create Job' %>
<% end %>

app/views/photography_jobs/show.html.erb
<h1><%= @photographyjob.title %></h1>

<p><%= @photographyjob.description %></p>

<% if(current_user.profile.photographer)%>
    <%= link_to "Apply to job", new_photography_job_job_application_path(@photographyjob) %>
<% end %>