config/routes.rb
Rails.application.routes.draw do
  resources :pending_applications
  resources :photography_jobs do 
    resources :job_applications
  end
  resources :job_applications
  root to: "home#index"
  resources :photography_jobs
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  resources :profiles, only: %i[edit update show]
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id                 :bigint           not null, primary key
#  city               :string
#  state              :string
#  street             :string
#  zip_code           :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  job_application_id :bigint           not null
#
# Indexes
#
#  index_addresses_on_job_application_id  (job_application_id)
#
# Foreign Keys
#
#  fk_rails_...  (job_application_id => job_applications.id)
#
class Address < ApplicationRecord
  belongs_to :job_application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_application.rb
# == Schema Information
#
# Table name: job_applications
#
#  id                 :bigint           not null, primary key
#  address            :string
#  email              :string
#  first_name         :string
#  last_name          :string
#  previous_employer  :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  photography_job_id :bigint           not null
#  user_id            :bigint           not null
#
# Indexes
#
#  index_job_applications_on_photography_job_id  (photography_job_id)
#  index_job_applications_on_user_id             (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (photography_job_id => photography_jobs.id)
#  fk_rails_...  (user_id => users.id)
#
class JobApplication < ApplicationRecord
  belongs_to :photography_job
  belongs_to :user
  has_one :address, dependent: :destroy
  
  accepts_nested_attributes_for :address
end

app/models/pending_application.rb
# == Schema Information
#
# Table name: pending_applications
#
#  id                 :bigint           not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  job_application_id :integer
#  photography_job_id :integer
#
class PendingApplication < ApplicationRecord

  belongs_to :job_application, dependent: :destroy
end

app/models/photographer.rb
# == Schema Information
#
# Table name: photographers
#
#  id         :bigint           not null, primary key
#  bio        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Photographer < ApplicationRecord
end

app/models/photography_job.rb
# == Schema Information
#
# Table name: photography_jobs
#
#  id          :bigint           not null, primary key
#  completed   :boolean          default(FALSE)
#  description :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#  users_id    :integer
#
# Indexes
#
#  index_photography_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class PhotographyJob < ApplicationRecord
  belongs_to :user
  has_many :applications
  has_many :pending_applications, through: :applications
  has_many :users, as: :applicants, through: :applications, dependent: :destroy
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  bio          :string
#  first_name   :string           default(""), not null
#  handle       :string           default(""), not null
#  last_name    :string           default(""), not null
#  photographer :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Profile<ApplicationRecord
    belongs_to :user
    has_one_attached :avatar
    
    def name 
        self.first_name + " " + self.last_name
    end 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_many :photography_jobs
  has_many :job_applications
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :photography_jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, only: %i[creaet new update edit destroy]

    def after_sign_in_path_for(user)
        profile_path(user.profile)
    end

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [profile_attributes: [:first_name,:last_name,:bio,:photographer]])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_user, only: %i[show edit update]
    before_action :profile_params, only: %i[update]
    

    def show 
    end

    def edit
    end

    def update
        if @profile.update(profile_params)
            redirect_to profile_path(@profile)
        else
            render 'edit'
        end
    end

    private
    
    def set_user
        @profile = Profile.find_by_id(params[:id])
    end

    def profile_params
        params.require(:profile).permit(:first_name,:last_name,:bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/pending_applications_helper.rb
module PendingApplicationsHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/helpers/photography_jobs_helper.rb
module PhotographyJobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="mt-auto">
	<p>&copy; This is footer</p>
</div>

app/views/layouts/_navigation.html.erb
  <div class="d-flex flex-row bg-dark justify-content-evenly">
  <h1 class="text-muted">Moments Captured</h1> 
  <ul class="nav justify-content-center  text-muted ">
    <% if current_user %> 
          <li class="nav-item">
            <%= link_to "My Profile", profile_path(current_user.profile),class:"nav-link  "%>
          </li>
          <% else%>
            <li class="nav-item"> 
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_url,class:"nav-link" %>
            </li>
          <% end%>
          <% if current_user %>
          <li class="nav-item">  
            <%= link_to 'Jobs', photography_jobs_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Job', new_photography_job_path, class:"nav-link"%>
          </li>
    <% end %>
    
</ul>
<% if current_user%>
            <li class="nav-item">
              <%= button_to 'Logout', destroy_user_session_url, method: :delete%>
            </li>
    <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MomentsCaptured</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='d-flex flex-column vh-100 justify-content-center bg-dark'>
      <%= render 'layouts/navigation' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer'%>
  </body>
</html>